CC = gcc
CFLAGS = -Wall -o

all: exercice1 exercice2

exercice1: exercice1.c
	$(CC) $(CFLAGS) exercice1.o exercice1.c

exercice2: exercice2.c
	$(CC) $(CFLAGS) exercice2.o exercice2.c

clean:
	rm -f *.o
