CC = gcc
CFLAGS = -Wall -o

all: exercice1 exercice2 exercice4

exercice1: exercice1.c
	$(CC) $(CFLAGS) exercice1.o exercice1.c

exercice2: exercice2.c
	$(CC) $(CFLAGS) exercice2.o exercice2.c

exercice4: exercice4.c
	$(CC) $(CFLAGS) exercice4.o exercice4.c
	
clean:
	rm -f *.o